services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: always

  app:
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      - database
      - docling-serve
    volumes:
      - app_data:/app/public/uploads
    ports:
      - "${NEXT_PUBLIC_PORT:-3000}:3000"
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV}
      NEXT_PUBLIC_DEPLOYMENT_ENV: ${NEXT_PUBLIC_DEPLOYMENT_ENV}

volumes:
  postgres_data:
  app_data:
